Consistent 4-spaces indents, with updated authors/maintainer headers

diff --git a/bash/scripts/shipit b/bash/scripts/shipit
--- a/bash/scripts/shipit
+++ b/bash/scripts/shipit
@@ -6,20 +6,22 @@
 # Script for generating Github release / tag assets
 # and managing release notes for a software pipeline
 #
-# author:  James Hunt <james@niftylogic.com>
-# created: 2016-03-30
+# original authors: James Hunt <james@niftylogic.com>
+#                   Geoff Franks (Stark & Wayne)
+# created:          2016-11-18
+# maintainer:       Benjamin Gandon (Gstack)
 
 auto_sed() {
-  file=$1
-  shift
-  cmd=$1
-  shift
+    file=$1
+    shift
+    cmd=$1
+    shift
 
-  if [[ "$(uname -s)" == "Darwin" ]]; then
-    sed -E -i='' -e "$cmd" ${file}
-  else
-    sed -r -i -e "$cmd" ${file}
-  fi
+    if [[ "$(uname -s)" == "Darwin" ]]; then
+        sed -E -i='' -e "$cmd" ${file}
+    else
+        sed -r -i -e "$cmd" ${file}
+    fi
 }
 
 set -eu
@@ -33,22 +35,22 @@ RELEASE_BRANCH=${RELEASE_BRANCH:-"master"}
 : ${REPO_OUT:?required}
 
 if [[ -z ${VERSION_FROM} ]]; then
-  echo >&2 "VERSION_FROM environment variable not set, or empty.  Did you misconfigure Concourse?"
-  exit 2
+    echo >&2 "VERSION_FROM environment variable not set, or empty. Did you misconfigure Concourse?"
+    exit 2
 fi
 if [[ ! -f ${VERSION_FROM} ]]; then
-  echo >&2 "Version file (${VERSION_FROM}) not found.  Did you misconfigure Concourse?"
-  exit 2
+    echo >&2 "Version file (${VERSION_FROM}) not found. Did you misconfigure Concourse?"
+    exit 2
 fi
 VERSION=$(cat ${VERSION_FROM})
 if [[ -z ${VERSION} ]]; then
-  echo >&2 "Version file (${VERSION_FROM}) was empty.  Did you misconfigure Concourse?"
-  exit 2
+    echo >&2 "Version file (${VERSION_FROM}) was empty. Did you misconfigure Concourse?"
+    exit 2
 fi
 
 if [[ ! -f ${REPO_ROOT}/ci/release_notes.md ]]; then
-  echo >&2 "ci/release_notes.md not found.  Did you forget to write them?"
-  exit 1
+    echo >&2 "ci/release_notes.md not found. Did you forget to write them?"
+    exit 1
 fi
 
 ###############################################################
@@ -60,14 +62,14 @@ pushd $REPO_ROOT
 mkdir artifacts
 
 if [[ ! -d ${BIN_DIR} ]]; then
-	echo "${BIN_DIR} does not exist as a directory inside ${REPO_ROOT}"
-	exit 1
+    echo "${BIN_DIR} does not exist as a directory inside ${REPO_ROOT}"
+    exit 1
 fi
 
 for bin in $(cd ${BIN_DIR} && ls ${BINARIES}); do
-  cp ${BIN_DIR}/${bin} artifacts/${bin}
-  auto_sed artifacts/${bin} "s/^VERSION=.*/VERSION=\"v${VERSION}\"/"
-  artifacts/${bin} -v | grep ${VERSION}
+    cp ${BIN_DIR}/${bin} artifacts/${bin}
+    auto_sed artifacts/${bin} "s/^VERSION=.*/VERSION=\"v${VERSION}\"/"
+    artifacts/${bin} -v | grep ${VERSION}
 done
 popd
 
@@ -83,19 +85,21 @@ EOF
 
 # GIT!
 if [[ -z $(git config --global user.email) ]]; then
-  git config --global user.email "${GIT_EMAIL}"
+    git config --global user.email "${GIT_EMAIL}"
 fi
 if [[ -z $(git config --global user.name) ]]; then
-  git config --global user.name "${GIT_NAME}"
+    git config --global user.name "${GIT_NAME}"
 fi
 
-(cd ${REPO_ROOT}
- git stash
- git merge --no-edit "${RELEASE_BRANCH}"
- git stash pop
- git add -A
- git status
- git commit -m "release v${VERSION}")
+(
+    cd ${REPO_ROOT}
+    git stash
+    git merge --no-edit "${RELEASE_BRANCH}"
+    git stash pop
+    git add -A
+    git status
+    git commit -m "release v${VERSION}"
+)
 
 # so that future steps in the pipeline can push our changes
 cp -a ${REPO_ROOT} ${REPO_OUT}/git
diff --git a/boshrelease/scripts/testflight b/boshrelease/scripts/testflight
--- a/boshrelease/scripts/testflight
+++ b/boshrelease/scripts/testflight
@@ -4,7 +4,8 @@
 #
 # Script for testing a BOSH release using bosh
 #
-# author:  James Hunt <james@niftylogic.com>
+# original author: James Hunt <james@niftylogic.com>
+# maintainer:      Benjamin Gandon (Gstack)
 
 set -eu
 
@@ -19,16 +20,16 @@ DEBUG=${DEBUG:-}
 script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 
 header() {
-	echo
-	echo "###############################################"
-	echo
-	echo $*
-	echo
+    echo
+    echo "###############################################"
+    echo
+    echo $*
+    echo
 }
 
 delete_deployment() {
-	header "Cleaning up deployment..."
-	bosh -n delete-deployment --force
+    header "Cleaning up deployment..."
+    bosh -n delete-deployment --force
 }
 trap "echo; echo; echo; sleep 10; delete_deployment" EXIT SIGINT SIGTERM
 
@@ -36,7 +37,7 @@ trap "echo; echo; echo; sleep 10; delete_deployment" EXIT SIGINT SIGTERM
 cd ${REPO_ROOT:?required}
 
 if [[ -f ".gitattributes" ]] && grep -qF "lfs" ".gitattributes"; then
-  git lfs install
+    git lfs install
 fi
 
 header "Pulling in any git submodules..."
@@ -46,8 +47,8 @@ header "Confirming testflight inputs"
 
 echo "Confirming deployment manifest ${MANIFEST_PATH} exists"
 if [[ ! -f ${MANIFEST_PATH} ]]; then
-	echo "Deployment manifest ${MANIFEST_PATH} does not exist"
-	exit 1
+    echo "Deployment manifest ${MANIFEST_PATH} does not exist"
+    exit 1
 fi
 
 echo "Confirming that \$MANIFEST_VARS is valid"
@@ -57,8 +58,8 @@ mkdir -p tmp
 # and will be converted to "key: value" YAML
 echo "${MANIFEST_VARS:-"{} ---"}" | sed -e "s/ *= */: /g" > tmp/vars.yml
 if [[ ! -z $DEBUG ]]; then
-	echo "Variables passed to deployment manifest:"
-	cat tmp/vars.yml
+    echo "Variables passed to deployment manifest:"
+    cat tmp/vars.yml
 fi
 # convert YAML to JSON to check YAML validity
 spruce json tmp/vars.yml > /dev/null
@@ -66,13 +67,13 @@ spruce json tmp/vars.yml > /dev/null
 echo "Confirming each operator file exists: ${MANIFEST_OP_PATHS:-ok, none specified.}"
 op_patch_file_errors=
 for op_patch_file in ${MANIFEST_OP_PATHS//,/ } ; do
-	if [[ ! -f $op_patch_file ]]; then
-		op_patch_file_errors=1
-		echo "Operator file missing: ${op_patch_file}"
-	fi
+    if [[ ! -f $op_patch_file ]]; then
+        op_patch_file_errors=1
+        echo "Operator file missing: ${op_patch_file}"
+    fi
 done
 if [[ ! -z ${op_patch_file_errors} ]]; then
-	exit 1
+    exit 1
 fi
 
 ${script_dir}/wait-until-proxy-bosh-cf-running
@@ -82,31 +83,31 @@ delete_deployment
 
 header "Creating candidate BOSH release..."
 if [[ -d dev_releases ]]; then
-  # in case dev_releases/ is in repo accidentally
-  if ! findmnt --mountpoint git/blobs > /dev/null; then
-    bosh -n reset-release
-  else
-    # When declaring the 'blobs/' directory as cached by Concourse, the
-    # 'blobs/' subdirectory is a mount point.
-    #
-    # First, we want the cache to be kept and not evicted, so we back it up.
-    mkdir -p ../cached-blobs
-    mv blobs/* ../cached-blobs/
+    # in case dev_releases/ is in repo accidentally
+    if ! findmnt --mountpoint git/blobs > /dev/null; then
+        bosh -n reset-release
+    else
+        # When declaring the 'blobs/' directory as cached by Concourse, the
+        # 'blobs/' subdirectory is a mount point.
+        #
+        # First, we want the cache to be kept and not evicted, so we back it up.
+        mkdir -p ../cached-blobs
+        mv blobs/* ../cached-blobs/
 
-    # Then, 'bosh reset-release' might fail at deleting the mounted volume.
-    # This happens when re-running the 'testflight' script in a 'fly hijack'
-    # session. The command still still properly performs the necessary
-    # deletions, so just ignore its error status.
-    bosh -n reset-release || true
+        # Then, 'bosh reset-release' might fail at deleting the mounted volume.
+        # This happens when re-running the 'testflight' script in a 'fly hijack'
+        # session. The command still still properly performs the necessary
+        # deletions, so just ignore its error status.
+        bosh -n reset-release || true
 
-    # Finally, we restore the contents of the cached directory.
-    mv ../cached-blobs/* blobs/
-  fi
+        # Finally, we restore the contents of the cached directory.
+        mv ../cached-blobs/* blobs/
+    fi
 fi
 
 blobstore_provider=$(bosh int config/final.yml --path /blobstore/provider)
 if [[ ${blobstore_provider} == "s3" && -n ${AWS_ACCESS_KEY} ]]; then
-	cat > config/private.yml <<YAML
+    cat > config/private.yml <<YAML
 ---
 blobstore:
   options:
@@ -116,15 +117,15 @@ YAML
 fi
 create_release_args=()
 if [[ "${IGNORE_GIT_DIRTY_STATE:-X}" != "X" \
-    && -n "$(git status --porcelain)" ]]; then
-  create_release_args+=("--force")
+        && -n "$(git status --porcelain)" ]]; then
+    create_release_args+=("--force")
 fi
 bosh create-release "${create_release_args[@]}"
 bosh upload-release --rebase
 
 header "Deploying to ${BOSH_ENVIRONMENT}..."
 release_name=$(bosh int config/final.yml --path /final_name 2> /dev/null) \
-  || release_name=$(bosh int config/final.yml --path /name)
+    || release_name=$(bosh int config/final.yml --path /name)
 
 header "Choosing cloud-config options"
 vm_type=$(bosh int <(bosh cloud-config) --path /vm_types/0/name)
@@ -148,19 +149,19 @@ cat > tmp/deployment.yml <<YAML
 YAML
 
 for ig_name in $(spruce json ${MANIFEST_PATH} | jq -r ".instance_groups[].name"); do
-  vm_resources=$(
-    bosh int "${MANIFEST_PATH}" --path "/instance_groups/name=${ig_name}/vm_resources"
-  )
-  if [[ -z "${vm_resources}" ]]; then
-    cat >> tmp/deployment.yml <<YAML
+    vm_resources=$(
+        bosh int "${MANIFEST_PATH}" --path "/instance_groups/name=${ig_name}/vm_resources"
+    )
+    if [[ -z "${vm_resources}" ]]; then
+        cat >> tmp/deployment.yml <<YAML
 - type: replace
   path: /instance_groups/name=${ig_name}/vm_type
   value: ${vm_type}
 
 YAML
-  fi
+    fi
 
-  cat >> tmp/deployment.yml <<YAML
+    cat >> tmp/deployment.yml <<YAML
 - type: replace
   path: /instance_groups/name=${ig_name}/networks
   value: [{name: ${network}}]
@@ -170,7 +171,7 @@ done
 
 instance_groups_with_persistent_disk_types=$(spruce json $MANIFEST_PATH | jq -r ".instance_groups[] | select(.persistent_disk_type).name")
 for ig_name in $instance_groups_with_persistent_disk_types; do
-	cat >> tmp/deployment.yml <<YAML
+    cat >> tmp/deployment.yml <<YAML
 - type: replace
   path: /instance_groups/name=${ig_name}/persistent_disk_type
   value: ${disk_type}
@@ -180,17 +181,17 @@ done
 
 op_patch_files_flags=""
 for op_patch_file in ${MANIFEST_OP_PATHS//,/ } ; do
-   op_patch_files_flags="${op_patch_files_flags} -o $op_patch_file"
+     op_patch_files_flags="${op_patch_files_flags} -o $op_patch_file"
 done
 
 set -x
 
 bosh int ${MANIFEST_PATH} \
-  -o tmp/deployment.yml    \
-  ${op_patch_files_flags}            \
-  --vars-store tmp/creds.yml \
-  --vars-file  tmp/vars.yml  \
-  --var-errs \
+        -o tmp/deployment.yml \
+        ${op_patch_files_flags} \
+        --vars-store tmp/creds.yml \
+        --vars-file tmp/vars.yml \
+        --var-errs \
     > tmp/manifest.yml
 
 bosh -n deploy tmp/manifest.yml
@@ -198,12 +199,12 @@ bosh -n deploy tmp/manifest.yml
 TEST_ERRAND=${TEST_ERRAND:-""} # backwards compatibility
 TEST_ERRANDS=${TEST_ERRANDS:-"${TEST_ERRAND}"}
 if [[ -n "${TEST_ERRANDS}" ]]; then
-	for errand in ${TEST_ERRANDS}; do
-		header "Running '${errand}' errand"
-		bosh -n run-errand ${errand}
-	done
+    for errand in ${TEST_ERRANDS}; do
+        header "Running '${errand}' errand"
+        bosh -n run-errand ${errand}
+    done
 else
-	echo "No test errands specified, skipping."
+    echo "No test errands specified, skipping."
 fi
 
 echo
diff --git a/buildpack/scripts/shipit b/buildpack/scripts/shipit
--- a/buildpack/scripts/shipit
+++ b/buildpack/scripts/shipit
@@ -6,6 +6,8 @@
 # Script for generating updating VERSION, preparing packaged buildpacks,
 # and managing release notes for a software pipeline
 #
+# original author: Dr Nic Williams (Stark & Wayne)
+# maintainer:      Benjamin Gandon (Gstack)
 
 : ${RELEASE_NAME:?required}
 : ${REPO_ROOT:?required}
@@ -19,18 +21,18 @@ RELEASE_BRANCH=${RELEASE_BRANCH:-"master"}
 : ${GIT_NAME:?required}
 
 if [[ ! -f ${VERSION_FROM} ]]; then
-  echo >&2 "Version file (${VERSION_FROM}) not found.  Did you misconfigure Concourse?"
-  exit 2
+    echo >&2 "Version file (${VERSION_FROM}) not found. Did you misconfigure Concourse?"
+    exit 2
 fi
 VERSION=$(cat ${VERSION_FROM})
 if [[ -z ${VERSION} ]]; then
-  echo >&2 "Version file (${VERSION_FROM}) was empty.  Did you misconfigure Concourse?"
-  exit 2
+    echo >&2 "Version file (${VERSION_FROM}) was empty. Did you misconfigure Concourse?"
+    exit 2
 fi
 
 if [[ ! -f ${REPO_ROOT}/ci/release_notes.md ]]; then
-  echo >&2 "ci/release_notes.md not found.  Did you forget to write them?"
-  exit 1
+    echo >&2 "ci/release_notes.md not found. Did you forget to write them?"
+    exit 1
 fi
 
 DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
@@ -62,15 +64,17 @@ EOF
 
 # GIT!
 if [[ -z $(git config --global user.email) ]]; then
-  git config --global user.email "${GIT_EMAIL}"
+    git config --global user.email "${GIT_EMAIL}"
 fi
 if [[ -z $(git config --global user.name) ]]; then
-  git config --global user.name "${GIT_NAME}"
+    git config --global user.name "${GIT_NAME}"
 fi
 
-(cd ${REPO_OUT}
- echo "${VERSION}" > VERSION
- git merge --no-edit ${RELEASE_BRANCH}
- git add -A
- git status
- git commit -m "release v${VERSION}")
+(
+    cd ${REPO_OUT}
+    echo "${VERSION}" > VERSION
+    git merge --no-edit ${RELEASE_BRANCH}
+    git add -A
+    git status
+    git commit -m "release v${VERSION}"
+)
diff --git a/go/scripts/shipit b/go/scripts/shipit
--- a/go/scripts/shipit
+++ b/go/scripts/shipit
@@ -6,9 +6,9 @@
 # Script for generating Github release / tag assets
 # and managing release notes for a software pipeline
 #
-# author:  James Hunt <james@niftylogic.com>
-# created: 2016-03-30
-#
+# original author: James Hunt <james@niftylogic.com>
+# created:         2016-03-30
+# maintainer:      Benjamin Gandon (Gstack)
 
 set -eu
 
@@ -24,22 +24,22 @@ RELEASE_BRANCH=${RELEASE_BRANCH:-"master"}
 : ${GIT_NAME:?required}
 
 if [[ -z ${VERSION_FROM} ]]; then
-  echo >&2 "VERSION_FROM environment variable not set, or empty.  Did you misconfigure Concourse?"
-  exit 2
+    echo >&2 "VERSION_FROM environment variable not set, or empty. Did you misconfigure Concourse?"
+    exit 2
 fi
 if [[ ! -f ${VERSION_FROM} ]]; then
-  echo >&2 "Version file (${VERSION_FROM}) not found.  Did you misconfigure Concourse?"
-  exit 2
+    echo >&2 "Version file (${VERSION_FROM}) not found. Did you misconfigure Concourse?"
+    exit 2
 fi
 VERSION=$(cat ${VERSION_FROM})
 if [[ -z ${VERSION} ]]; then
-  echo >&2 "Version file (${VERSION_FROM}) was empty.  Did you misconfigure Concourse?"
-  exit 2
+    echo >&2 "Version file (${VERSION_FROM}) was empty. Did you misconfigure Concourse?"
+    exit 2
 fi
 
 if [[ ! -f ${REPO_ROOT}/ci/release_notes.md ]]; then
-  echo >&2 "ci/release_notes.md not found.  Did you forget to write them?"
-  exit 1
+    echo >&2 "ci/release_notes.md not found. Did you forget to write them?"
+    exit 1
 fi
 
 ###############################################################
@@ -51,18 +51,18 @@ ROOT=$( cd "$( dirname "${BASH_SOURCE[0]}" )/../.." && pwd )
 
 newgopath=${ROOT%%/gopath/*}/gopath
 if [[ -d ${newgopath} ]]; then
-	if [[ -z ${GOPATH} ]]; then
-		GOPATH="${newgopath}"
-	else
-		GOPATH="${newgopath}:${GOPATH}"
-	fi
-	PATH="${PATH}:${newgopath}/bin"
+    if [[ -z ${GOPATH} ]]; then
+        GOPATH="${newgopath}"
+    else
+        GOPATH="${newgopath}:${GOPATH}"
+    fi
+    PATH="${PATH}:${newgopath}/bin"
 fi
 echo ">> Using GOPATH ${GOPATH}"
 go install github.com/mitchellh/gox@latest
 
 if [[ -n ${STATIC_BINARY} && ${STATIC_BINARY} != "false" ]]; then
-	export CGO_ENABLED=0
+    export CGO_ENABLED=0
 fi
 
 pushd $REPO_ROOT
@@ -84,17 +84,19 @@ EOF
 
 # GIT!
 if [[ -z $(git config --global user.email) ]]; then
-  git config --global user.email "${GIT_EMAIL}"
+    git config --global user.email "${GIT_EMAIL}"
 fi
 if [[ -z $(git config --global user.name) ]]; then
-  git config --global user.name "${GIT_NAME}"
+    git config --global user.name "${GIT_NAME}"
 fi
 
-(cd ${REPO_ROOT}
- git merge --no-edit "${RELEASE_BRANCH}"
- git add -A
- git status
- git commit -m "release v${VERSION}")
+(
+    cd ${REPO_ROOT}
+    git merge --no-edit "${RELEASE_BRANCH}"
+    git add -A
+    git status
+    git commit -m "release v${VERSION}"
+)
 
 # so that future steps in the pipeline can push our changes
 cp -a ${REPO_ROOT} ${REPO_OUT}/git
diff --git a/helm/scripts/shipit b/helm/scripts/shipit
--- a/helm/scripts/shipit
+++ b/helm/scripts/shipit
@@ -6,17 +6,18 @@
 # Script for finalizing and packaging Helm chart
 # and managing release notes
 #
-# author:  Dr Nic Williams <drnicwilliams@gmail.com>
-# created: 2018-11-09
+# original author: Dr Nic Williams <drnicwilliams@gmail.com>
+# created:         2018-11-09
+# maintainer:      Benjamin Gandon (Gstack)
 
 set -eu
 
 header() {
-	echo
-	echo "###############################################"
-	echo
-	echo $*
-	echo
+    echo
+    echo "###############################################"
+    echo
+    echo $*
+    echo
 }
 
 : ${CHART_NAME:?required}
@@ -37,18 +38,18 @@ RELEASE_BRANCH=${RELEASE_BRANCH:-"master"}
 HELM_VERSION=2.11.0
 
 if [[ ! -f ${VERSION_FROM} ]]; then
-  echo >&2 "Version file (${VERSION_FROM}) not found.  Did you misconfigure Concourse?"
-  exit 2
+    echo >&2 "Version file (${VERSION_FROM}) not found. Did you misconfigure Concourse?"
+    exit 2
 fi
 VERSION=$(cat ${VERSION_FROM})
 if [[ -z ${VERSION} ]]; then
-  echo >&2 "Version file (${VERSION_FROM}) was empty.  Did you misconfigure Concourse?"
-  exit 2
+    echo >&2 "Version file (${VERSION_FROM}) was empty. Did you misconfigure Concourse?"
+    exit 2
 fi
 
 if [[ ! -f ${REPO_ROOT}/ci/release_notes.md ]]; then
-  echo >&2 "ci/release_notes.md not found.  Did you forget to write them?"
-  exit 1
+    echo >&2 "ci/release_notes.md not found. Did you forget to write them?"
+    exit 1
 fi
 
 DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
@@ -72,7 +73,7 @@ popd
 header "Install helm"
 curl -LO https://storage.googleapis.com/kubernetes-helm/helm-v${HELM_VERSION}-linux-amd64.tar.gz
 tar xfz helm-*.tar.gz
-mv linux-amd64/helm  /usr/local/bin
+mv linux-amd64/helm /usr/local/bin
 helm version --client
 helm init --client-only
 
@@ -93,10 +94,10 @@ popd
 
 header "Update git repo with final release..."
 if [[ -z $(git config --global user.email) ]]; then
-  git config --global user.email "${GIT_EMAIL}"
+    git config --global user.email "${GIT_EMAIL}"
 fi
 if [[ -z $(git config --global user.name) ]]; then
-  git config --global user.name "${GIT_NAME}"
+    git config --global user.name "${GIT_NAME}"
 fi
 
 echo "v${VERSION}"                 > ${RELEASE_ROOT}/tag
@@ -104,10 +105,10 @@ echo "v${VERSION}"                 > ${RELEASE_ROOT}/name
 mv ${REPO_OUT}/ci/release_notes.md   ${RELEASE_ROOT}/notes.md
 
 pushd $REPO_OUT
-git merge --no-edit "${RELEASE_BRANCH}"
-git add -A
-git status
-git commit -m "release v${VERSION}"
+    git merge --no-edit "${RELEASE_BRANCH}"
+    git add -A
+    git status
+    git commit -m "release v${VERSION}"
 popd
 
 cat > ${NOTIFICATION_OUT:-notifications}/message <<EOS
